### ISSUE TITLE
Caching Material Icons

### ISSUE THREAD

**Issue by SteffenDE** [NekR/offline-plugin#309]
I'm currently using the following config for a SPA:
```javascript
new OfflinePlugin({
  responseStrategy: 'network-first',
  AppCache: false,
  externals: [
    '/',
    'https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,400italic',
    'https://fonts.googleapis.com/icon?family=Material+Icons',
    'https://unpkg.com/mdi@2.0.46/css/materialdesignicons.min.css'
  ],
  excludes: ['**/*.map'],
  ServiceWorker: {
    events: true,
    navigateFallbackURL: '/'
  }
})
```
Using this, I'm encountering the problem that `https://fonts.googleapis.com/icon?family=Material+Icons` requests another font file:
```css
/* fallback */
@font-face {
  font-family: 'Material Icons';
  font-style: normal;
  font-weight: 400;
  src: url(https://fonts.gstatic.com/s/materialicons/v29/2fcrYFNaTjcS6g4U3t-Y5UEw0lE80llgEseQY3FEmqw.woff2) format('woff2');
}
...
```
Because this url is not static is there any way to tell the plugin to cache requests to `https://fonts.gstatic.com/s/materialicons/*/*.woff2` **after** the request is done the first time?
I tried adding this pattern to the optional cache section but despite from showing a warning that external urls should be inside the externals option it didn't work as expected.

Thanks for any help!
